---
development:
  dialect: postgres
  host: {{envOr "DATABASE_HOST" "127.0.0.1"}}
  port: {{envOr "DATABASE_PORT" "5432"}}
  user: {{envOr "DATABASE_USER" "root"}}
  password: {{envOr "DATABASE_PASSWORD" ""}}
  database: {{envOr "DATABASE_NAME" "bxauth0-dev"}}
  pool: {{envOr "DATABASE_POOL_SIZE" "5"}}
