grpc:
  host: {{ or .GRPC_BIND_ADDRESS "0.0.0.0" }}
  port: {{ or .GRPC_BIND_PORT 9090 }}
http:
  host: {{ or .HTTP_BIND_ADDRESS "0.0.0.0" }}
  port: {{ or .HTTP_BIND_PORT 4080 }}
database:
  host: {{ or .DATABASE_HOST "127.0.0.1" }}
  port: {{ or .DATABASE_PORT 5432 }}
  user: {{ or .DATABASE_USER "root" }}
  password: {{ or .DATABASE_PASSWORD "" }}
  name: {{ or .DATABASE_NAME "bxauth0-dev" }}
  pool: {{ or .DATABASE_POOL_SIZE 5 }}
  sslmode: {{ or .DATABASE_SSLMODE "disable" }}
endpoint: {{ or .ENDPOINT "http://localhost:4080" }}
client_id: {{ or .AUTH0_CLIENT_ID "blueXauth0" }}
client_secret: {{ or .AUTH0_CLIENT_SECRET "YouShallNotPass" }}
client_email: {{ or .AUTH0_CLIENT_EMAIL "admin@example.com" }}
